spring.application.name=backend

# Base de datos (Docker local o nube)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pasteleria_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Lima}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=${JWT_SECRET:EsteEsUnSecretoLocalSoloParaDesarrolloPasteleria1234567890}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}

# Puerto cloud
server.port=${PORT:8080}