spring.application.name=backend


# ===============================
# DATABASE CLOUD (AIVEN / RENDER)
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ===============================
# JWT
# ===============================

app.jwt.secret=${JWT_SECRET:EsteEsUnSecretoLocalSoloParaDesarrolloPasteleria1234567890}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}


# ===============================
# SERVER
# ===============================

server.port=${PORT:8080}


# ===============================
# CORS
# ===============================

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}